name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Run Luacheck
      uses: nebularg/actions-luacheck@v1
      with:
        args: --no-color -q
        annotate: warning
        
    - name: Create Package
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo apt-get install pandoc
        curl -s https://raw.githubusercontent.com/Gethe/packager/RealUI/release.sh -o release.sh
        bash release.sh -L -p 88269 -w 16068
