name: Luacheck

on: [push, pull_request]

jobs:
  pull_request:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Run Luacheck
      uses: nebularg/actions-luacheck@v1
      with:
        args: --no-color -q
        annotate: warning
