name: Nightly Alpha

on:
  workflow_dispatch:
#on:
#  schedule:
#    - cron: '0 7 * * *'

jobs:
  nightly:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Alpha Changelog
      if: contains(github.ref, 'tags') != true
      run: |
        echo $GITHUB_REF
        rm -f CHANGELOG.md

    - name: Get build version
      id: version
      uses: craig-day/compute-tag@v10
      with:
        github_token: ${{ github.token }}

    - name: Commit tagger
      uses: tvdias/github-tagger@v0.0.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.version.outputs.next_tag }}

    - name: Create Package
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -s https://raw.githubusercontent.com/Gethe/packager/RealUI/release.sh -o release.sh
        bash release.sh -L -p 88269
