name: Nightly Alpha

on:
  schedule:
    - cron: '0 7 * * *'

jobs:
  nightly:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create Package
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo apt-get install pandoc
        curl -s https://raw.githubusercontent.com/Gethe/packager/RealUI/release.sh -o release.sh
        bash release.sh -L -p 88269
