name: Tag Beta

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Run Luacheck
      uses: nebularg/actions-luacheck@v1
      with:
        args: --no-color -q
        annotate: warning

    - name: Check
      run: |
        echo ${{ github.event }}
        echo ${{ github.event_name }}
        echo ${{ github.event_path }}
        echo ${{ github.ref }}

    - name: Set beta
      id: beta
      uses: onemedical/action-general-autotag@main
      with:
        GITHUB_TOKEN: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
        source_file: "nibRealUI/nibRealUI.toc"
        extraction_regex: "\\s*##\\s*Version\\s*:\\s*(\\d+\\.\\d+\\.\\d+)"
        tag_format: "{version}.${{ github.run_number }}-beta"
        tag_message: "beta"
